# -*- coding: utf-8 -*-
"""Voice/KWS configuration.

Paths point to the existing sherpa project models by default.  Override with
environment variables if you want to keep the voice library portable.
"""
import os

# Sherpa streaming transducer KWS model directory
SHERPA_MODEL_DIR = os.environ.get(
    "SHERPA_MODEL_DIR",
    "/home/time/work/sherpa/models/sherpa-onnx-kws-zipformer-zh-en-3M-2025-12-20",
)

# Token-formatted keyword file (generated by sherpa-onnx-cli text2token)
KEYWORDS_FILE = os.environ.get(
    "SHERPA_KEYWORDS",
    os.path.join(os.path.dirname(__file__), "keywords.txt"),
)

# Silero VAD front-end (optional but recommended)
SILERO_VAD_MODEL = os.environ.get(
    "SHERPA_VAD_MODEL",
    "/home/time/work/sherpa/models/silero_vad.onnx",
)

# Audio parameters
VOICE_SAMPLE_RATE = int(os.environ.get("SHERPA_SAMPLE_RATE", "16000"))
VOICE_CAPTURE_RATE = int(os.environ.get("SHERPA_CAPTURE_RATE", "48000"))
VOICE_CHANNELS = int(os.environ.get("SHERPA_CHANNELS", "2"))
VOICE_BLOCKSIZE = int(os.environ.get("SHERPA_BLOCKSIZE", "1024"))
VOICE_DEVICE_ID = int(os.environ.get("SHERPA_DEVICE_ID", "6"))

# KWS decoder parameters
VOICE_PROVIDER = os.environ.get("SHERPA_PROVIDER", "cpu")  # 'cpu' is safe; 'openvino' needs custom build
VOICE_KEYWORDS_SCORE = float(os.environ.get("SHERPA_KEYWORDS_SCORE", "1.0"))
VOICE_KEYWORDS_THRESHOLD = float(os.environ.get("SHERPA_KEYWORDS_THRESHOLD", "0.25"))
VOICE_NUM_TRAILING_BLANKS = int(os.environ.get("SHERPA_NUM_TRAILING_BLANKS", "1"))
VOICE_NUM_THREADS = int(os.environ.get("SHERPA_NUM_THREADS", "2"))

# VAD parameters
VOICE_USE_VAD = os.environ.get("SHERPA_USE_VAD", "1") == "1"
# The default Silero VAD threshold of 0.5 is too aggressive for quiet USB mics
# and causes the KWS stream to be reset inside a keyword.  Lower the threshold
# and increase the hangover so VAD stays true across short pauses / weak phones.
VOICE_VAD_THRESHOLD = float(os.environ.get("SHERPA_VAD_THRESHOLD", "0.3"))
VOICE_VAD_HANGOVER_MS = float(os.environ.get("SHERPA_VAD_HANGOVER_MS", "800.0"))

# Even with a lenient VAD, a brief false negative inside a keyword would reset
# the KWS stream and drop the audio.  We therefore decode every block and only
# reset after VAD has been silent for this many consecutive blocks.
VOICE_SILENCE_RESET_BLOCKS = int(os.environ.get("SHERPA_SILENCE_RESET_BLOCKS", "10"))

# Digital gain / AGC parameters
# Some USB mics still capture too quietly even with ALSA AGC maxed.  Enable
# software auto-gain to lift speech blocks up to a target RMS level.
VOICE_GAIN = float(os.environ.get("SHERPA_GAIN", "1.0"))
VOICE_AUTO_GAIN = os.environ.get("SHERPA_AUTO_GAIN", "1") == "1"
VOICE_AUTO_GAIN_TARGET_DB = float(os.environ.get("SHERPA_AUTO_GAIN_TARGET_DB", "-20.0"))
VOICE_AUTO_GAIN_MAX_DB = float(os.environ.get("SHERPA_AUTO_GAIN_MAX_DB", "30.0"))
VOICE_AUTO_GAIN_MIN_DB = float(os.environ.get("SHERPA_AUTO_GAIN_MIN_DB", "-55.0"))
